### ISSUE TITLE
Visualize the salience and parsing imgae

### ISSUE THREAD

**Issue by victor-gui** [RQuispeC/saliency-semantic-parsing-reid#2]
Thanks for your work,I am wondering how should I do if I want to visualize the salience and parsing imgae?Can you release the code? Thank you very much!

**Comment by RQuispeC** [comment]
As pointed in the README, you can download the salience and semantic parsing maps from
https://drive.google.com/file/d/1lKxZOsdh2F3jOHeebO3JExQLyqSbecKi/view
https://drive.google.com/file/d/1EJY1HewqTN362JrxCPpUkFCVkNpdprT3/view
https://drive.google.com/file/d/14fk9lOQzcJaJBCTsLmXaAcwHkh6LLjwu/view
