### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by YachaoDong** [RQuispeC/saliency-semantic-parsing-reid#3]
I use python 3.6, pytorch 1.1.0.

**Comment by RQuispeC** [comment]
Hi Yachao

did you udpate anything in the code?, it seems that this error is due a non ascii character

Check out [this](https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte)

it seems that there may be an error in python 3.6:
Fix your locale: [How to solve UnicodeDecodeError in Python 3.6](https://stackoverflow.com/questions/51026315/how-to-solve-unicodedecodeerror-in-python-3-6/51027262#51027262)?

**Comment by YachaoDong** [comment]
Thank U for your reply, I have solved this prob. Maybe there is something wrong in dataset_loader.py, line 179, it should be self.transform_salience_parsing not self.transform_salience. You can check it .

**Comment by RQuispeC** [comment]
thanks for pointing out that bug, It has been fixed.
